# docker-compose.yml
services:
  frontend:
    build: .
    container_name: my-todo-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080  # Spring Boot が別で立ってる前提
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
